init:
  - git config --global core.autocrlf false

clone_depth: 5

environment:
  PYTHON: "C:\\Python35"
  access_token:
    secure: VMFbecLLHzDq/09YDPbcM0VDDSwwgY57vr5GXK6cZZ4Ti/Xs5RZoylzV8MMr1350

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

build_script:
  - cd doc\sphinx 

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %GIT_CONTENT_REPO_URL% %TEMP%\azure-cli-content
  - cmd: >-
    if exist %TEMP%\azure-cli-content\%YML_OUTPUT_FOLDER%
          (
            cd %TEMP%\azure-cli-content\%YML_OUTPUT_FOLDER%
            for /d %%p IN (*) do rmdir "%%p" /s /q
            echo %FILES_TO_DELETE%
            del %FILES_TO_DELETE% /f /q
          )
  - cd %TEMP%\azure-cli-content
  - SETLOCAL EnableDelayedExpansion & robocopy %TEMP%\azure-cli-xml2yml\yml-output %TEMP%\azure-cli-content\%YML_OUTPUT_FOLDER% /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (exit 1)
  - git add -A
  - git diff --quiet --exit-code --cached || git commit -m "Update Document Content" && git push origin %TARGET_BRANCH% && appveyor AddMessage "Document Updated"
