init:
  - git config --global core.autocrlf false

clone_depth: 5

environment:
  access_token:
    secure: VMFbecLLHzDq/09YDPbcM0VDDSwwgY57vr5GXK6cZZ4Ti/Xs5RZoylzV8MMr1350

install:
  - echo %APPVEYOR_REPO_NAME%
  - echo %APPVEYOR_REPO_BRANCH%
  - echo %APPVEYOR_PULL_REQUEST_NUMBER%
  - echo %APPVEYOR_PULL_REQUEST_TITLE%
  - python -m pip install -r requirements.txt
  - python -m pip install -e . # Install the CLI as a package
  - python -m pip install sphinx
  - python scripts/command_modules/install.py # Install the command modules as packages

build_script:
  - cd doc\sphinx 
  - make xml

artifacts:
  - path: doc\sphinx\_build

